version: '3.8'

services:
  backend:
    build: ./backend
    container_name: file_share_backend
    ports:
      - "8000:8000"
    volumes:
      - uploads_prod:/app/test_storage
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: file_share_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  uploads_prod: