version: '3.8'

services:
  backend:
    build: ./backend
    container_name: file_share_backend_dev
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - uploads_dev:/app/test_storage
    environment:
      - UPLOAD_DIR=/app/test_storage

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: file_share_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  uploads_dev: